server:
  error:
    include-message: always
    include-stacktrace: never

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false