server:
  port: 8080

spring:
  database: H2
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      #            use-new-id-generator-mappings: false
      format_sql: true
      ddl-auto: create-drop
      pool_size: 50