server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://root:1234@localhost:3306/heladeria?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false