server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://root:root@localhost:3306/heladeria
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false